### ISSUE TITLE
The code maybe result in some wrong.

### ISSUE THREAD

**Issue by hyunsooda** [zwei2/system_programming#3]
Source of problem: https://github.com/zwei2/system_programming/blob/master/hw8_skeleton.c

1. Problem 
Assume that file size is 26bytes and nthread is 5 then len(line number 77) will be 5.
where is 1byte? you lost 1byte.
one more... assume that file size is 27bytes and nthread is 5 then len will be 5 and you lost 2 bytes again.
the solution is that you have to handle remaining bytes using **moduler** calculating.

2. Problem (what ...)

106, 107 line
```
for(i=0;i<nthreads;i++)
    pthread_join(threads[i], NULL);
```
the time which program execute above line is when only one thread is terminated
the code must be revised.

3. Problem(actually it's not problem currently in your program. but it is not good pattern in terms of multi-threading programming)

The line of problem are 166,167.
```
pthread_cond_signal(&flag);
pthread_mutex_unlock(&lock);
```
you are releasing two lock simultaneously. if so, programmer cannot predict next code which will be executed. you can see deadlock if you insert sleep function before 110 line.

**Comment by yyoungha** [comment]
Thank you for your interest in my repository.
First, I didn't intend to upload this file because it was for homework.
As the file name says, it was just a skeleton file and it would have been very flawed. There are many other problems besides what you have pointed out, so if you are interested, look for more.
